### ISSUE TITLE
Add Information Flow to Design

### ISSUE THREAD

**Issue by sean-chester** [ethan-mcnamara/lock-free-programming#6]
_Consider adding a data flow diagram (DFD) to the engineering design_

 - The current design document features a solid UML diagram showing the class structures, which defines possible states for objects in the system
 - What is not very clear from the UML alone is how the classes interact with each other, in particular how they share (or synchronise) data
 - A DFD is an alternative diagram that can be used in _[functional analysis](https://en.wikibooks.org/wiki/Seed_Factories/Functions)_ to illustrate the processes that take place and how information flows between processes. It is described well in Chapter 8 of [Batini et al. (1992)](https://dl.acm.org/doi/book/10.5555/120331).
 - Including a functional schema (ideally as a DFD) in the design document may help clarify what data is communicated between classes, whether any of it (e.g., the set of events) is stored in a log, and where the potential for synchronisation might arise 

[BCN92] Batini et al. (1992). _Conceptual database design: an Entity-relationship approach_ Benjamin-Cummings Publishing Co., Inc. https://dl.acm.org/doi/book/10.5555/120331

**Comment by sean-chester** [comment]
PS. I suggest [a callback design](https://stackoverflow.com/a/28689902/2769271) for your async event handler.

**Comment by ethan-mcnamara** [comment]
Data flow diagram has been added to design doc

Also, the callback design link has been added to issue #9 as it will be useful for that task
